name: test

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - run: Rscript -e 'install.packages("testthat", "lintr")'
      - run: Rscript -e 'testthat::test_dir("tests/", stop_on_failure = T)'
      - run: Rscript -e "errors <- lintr::lint('utils.R'); print(errors); quit(save = 'no', status = length(errors))"
